services:
  - type: web
    name: mtsbu-parser
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_CHAT_ID
        sync: false
